In [1]:
import torch 
torch.__version__

c:\Users\Admin\AppData\Local\Programs\Python\Python313\Lib\site-packages\torch\cuda\__init__.py:64: FutureWarning: The pynvml package is deprecated. Please install nvidia-ml-py instead. If you did not install pynvml directly, please report this to the maintainers of the package that installed pynvml for you.
  import pynvml  # type: ignore[import]


'2.13.0+cpu'

In [2]:
scaler = torch.tensor(3)
scaler

tensor(3)

In [3]:
scaler.ndim

0

In [6]:
scaler.item()

3

In [15]:
## vectors
vector = torch.tensor([1,3])
vector

tensor([1, 3])

In [8]:
vector.ndim

1

In [17]:
vector.shape

torch.Size([2])

In [18]:
## matrix
MATRIX = torch.tensor([[2,4]
                       ,[4,7]])
MATRIX

tensor([[2, 4],
        [4, 7]])

In [19]:
MATRIX.ndim

2

In [20]:
MATRIX.shape

torch.Size([2, 2])

In [32]:
TENSOR = torch.tensor([[[2,3,5],
                        [6,7,4],
                        [2,4,2]]])
TENSOR

tensor([[[2, 3, 5],
         [6, 7, 4],
         [2, 4, 2]]])

In [33]:
TENSOR.ndim

3

In [34]:
TENSOR.shape

torch.Size([1, 3, 3])

In [38]:
random_tensor = torch.rand(size=(3,5))
random_tensor , random_tensor.dtype ,random_tensor.grad_dtype

(tensor([[0.6371, 0.7329, 0.7282, 0.4780, 0.1946],
         [0.2204, 0.0425, 0.3523, 0.8446, 0.5282],
         [0.1804, 0.9872, 0.3637, 0.7175, 0.9603]]),
 torch.float32,
 torch.float32)

In [42]:
CNN = torch.rand(size=(224,224,3))
CNN.shape , CNN.ndim,#CNN

(torch.Size([224, 224, 3]), 3)

In [44]:
zeros = torch.zeros(size=(2,3,4))
zeros , zeros.ndim , zeros.shape

(tensor([[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],
 
         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]]),
 3,
 torch.Size([2, 3, 4]))

In [45]:
ones = torch.ones(size=(2,4))
ones , ones.dtype , ones.ndim

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32,
 2)

In [49]:
ranges = torch.range(1,100,20)
arranges = torch.arange(1,100,5)
ranges , ranges.ndim , arranges

C:\Users\Admin\AppData\Local\Temp\ipykernel_8108\2256492807.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  ranges = torch.range(1,100,20)


(tensor([ 1., 21., 41., 61., 81.]),
 1,
 tensor([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81, 86,
         91, 96]))

In [53]:
zero_like = torch.zeros_like(ranges)
zeross = torch.zeros(ranges.shape)
zero_like ,zeross

(tensor([0., 0., 0., 0., 0.]), tensor([0., 0., 0., 0., 0.]))

In [56]:
float_32bit = torch.tensor([4,5,8],
                           dtype=torch.half,
                           device=None,
                           requires_grad=False)

float_32bit.ndim , float_32bit.shape , float_32bit.device , float_32bit.dtype

(1, torch.Size([3]), device(type='cpu'), torch.float16)

In [61]:
some_tensor = torch.rand(4,3)

print(f"tensors are \n {some_tensor}")
print(f"Shape of this tensor : {some_tensor.shape}")
print(f"Datatype of tensor : {some_tensor.dtype}")
print(f"Tensor is stored on {some_tensor.device}")

tensors are 
 tensor([[0.6955, 0.0815, 0.7264],
        [0.4326, 0.8655, 0.1646],
        [0.4308, 0.7276, 0.2751],
        [0.7579, 0.1978, 0.6298]])
Shape of this tensor : torch.Size([4, 3])
Datatype of tensor : torch.float32
Tensor is stored on cpu


In [62]:
### operation on tensor

tensors = torch.tensor([1,3,6])
tensors + 10

tensor([11, 13, 16])

In [63]:
tensors * 10

tensor([10, 30, 60])

In [64]:
tensors - 10

tensor([-9, -7, -4])

In [65]:
##multi func
torch.multiply(tensors,12)

tensor([12, 36, 72])

In [70]:
print(tensors ,"*" ,tensors)
print("is" , tensors*tensors)
print("is" , torch.multiply(tensors,tensors))

tensor([1, 3, 6]) * tensor([1, 3, 6])
is tensor([ 1,  9, 36])
is tensor([ 1,  9, 36])


In [73]:
tensor = torch.tensor([2,4,6])
tensors.shape

torch.Size([3])

In [75]:
torch.matmul(tensor,tensor) , tensor@tensor

(tensor(56), tensor(56))

In [78]:
%%time

for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
value

CPU times: total: 0 ns
Wall time: 77.5 μs


NameError: name 'value' is not defined