In [2]:
import torch 
torch.__version__

c:\Users\Admin\AppData\Local\Programs\Python\Python313\Lib\site-packages\torch\cuda\__init__.py:64: FutureWarning: The pynvml package is deprecated. Please install nvidia-ml-py instead. If you did not install pynvml directly, please report this to the maintainers of the package that installed pynvml for you.
  import pynvml  # type: ignore[import]


'2.13.0+cpu'

In [3]:
scaler = torch.tensor(3)
scaler

tensor(3)

In [4]:
scaler.ndim

0

In [5]:
scaler.item()

3

In [6]:
## vectors
vector = torch.tensor([1,3])
vector

tensor([1, 3])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
## matrix
MATRIX = torch.tensor([[2,4]
                       ,[4,7]])
MATRIX

tensor([[2, 4],
        [4, 7]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
TENSOR = torch.tensor([[[2,3,5],
                        [6,7,4],
                        [2,4,2]]])
TENSOR

tensor([[[2, 3, 5],
         [6, 7, 4],
         [2, 4, 2]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
random_tensor = torch.rand(size=(3,5))
random_tensor , random_tensor.dtype ,random_tensor.grad_dtype

(tensor([[0.0255, 0.2725, 0.1323, 0.4586, 0.6729],
         [0.2979, 0.4231, 0.2664, 0.6341, 0.9409],
         [0.0170, 0.0073, 0.4946, 0.3362, 0.7753]]),
 torch.float32,
 torch.float32)

In [16]:
CNN = torch.rand(size=(224,224,3))
CNN.shape , CNN.ndim,#CNN

(torch.Size([224, 224, 3]), 3)

In [17]:
zeros = torch.zeros(size=(2,3,4))
zeros , zeros.ndim , zeros.shape

(tensor([[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],
 
         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]]),
 3,
 torch.Size([2, 3, 4]))

In [18]:
ones = torch.ones(size=(2,4))
ones , ones.dtype , ones.ndim

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32,
 2)

In [19]:
ranges = torch.range(1,100,20)
arranges = torch.arange(1,100,5)
ranges , ranges.ndim , arranges

C:\Users\Admin\AppData\Local\Temp\ipykernel_16824\2256492807.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  ranges = torch.range(1,100,20)


(tensor([ 1., 21., 41., 61., 81.]),
 1,
 tensor([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81, 86,
         91, 96]))

In [20]:
zero_like = torch.zeros_like(ranges)
zeross = torch.zeros(ranges.shape)
zero_like ,zeross

(tensor([0., 0., 0., 0., 0.]), tensor([0., 0., 0., 0., 0.]))

In [21]:
float_32bit = torch.tensor([4,5,8],
                           dtype=torch.half,
                           device=None,
                           requires_grad=False)

float_32bit.ndim , float_32bit.shape , float_32bit.device , float_32bit.dtype

(1, torch.Size([3]), device(type='cpu'), torch.float16)

In [22]:
some_tensor = torch.rand(4,3)

print(f"tensors are \n {some_tensor}")
print(f"Shape of this tensor : {some_tensor.shape}")
print(f"Datatype of tensor : {some_tensor.dtype}")
print(f"Tensor is stored on {some_tensor.device}")

tensors are 
 tensor([[0.5796, 0.3014, 0.5796],
        [0.6345, 0.1938, 0.9745],
        [0.2997, 0.1418, 0.0208],
        [0.9506, 0.3865, 0.5279]])
Shape of this tensor : torch.Size([4, 3])
Datatype of tensor : torch.float32
Tensor is stored on cpu


In [23]:
### operation on tensor

tensors = torch.tensor([1,3,6])
tensors + 10

tensor([11, 13, 16])

In [24]:
tensors * 10

tensor([10, 30, 60])

In [25]:
tensors - 10

tensor([-9, -7, -4])

In [26]:
##multi func
torch.multiply(tensors,12)

tensor([12, 36, 72])

In [27]:
print(tensors ,"*" ,tensors)
print("is" , tensors*tensors)
print("is" , torch.multiply(tensors,tensors))

tensor([1, 3, 6]) * tensor([1, 3, 6])
is tensor([ 1,  9, 36])
is tensor([ 1,  9, 36])


In [28]:
tensorss = torch.tensor([2,4,6])
tensors.shape

torch.Size([3])

In [29]:
torch.matmul(tensorss,tensorss) , tensorss@tensorss

(tensor(56), tensor(56))

In [30]:
%%time

value = 0
for i in range(len(tensors)):
    value += tensors[i] * tensors[i]
value

CPU times: total: 0 ns
Wall time: 860 μs


tensor(46)

In [31]:
%%time

torch.matmul(tensors,tensors)

CPU times: total: 0 ns
Wall time: 109 μs


tensor(46)

In [32]:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]],dtype=torch.float32)

tensor_B = torch.tensor([[7,8],
                         [9,10],
                         [11,12]],dtype=torch.float32)


a= torch.matmul(tensor_A,tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [33]:
print(tensor_B.T)

tensor([[ 7.,  9., 11.],
        [ 8., 10., 12.]])


In [34]:
print(f"old shape of tensor_A {tensor_A.shape} and tensor_B {tensor_B.shape}")
print(f"new shape of tensor_b is {tensor_B.T.shape}")
print(f"multiplying {tensor_A} and {tensor_B.T}")
print("output \n")
output = torch.matmul(tensor_A,tensor_B.T)
print(output)

old shape of tensor_A torch.Size([3, 2]) and tensor_B torch.Size([3, 2])
new shape of tensor_b is torch.Size([2, 3])
multiplying tensor([[1., 2.],
        [3., 4.],
        [5., 6.]]) and tensor([[ 7.,  9., 11.],
        [ 8., 10., 12.]])
output 

tensor([[ 23.,  29.,  35.],
        [ 53.,  67.,  81.],
        [ 83., 105., 127.]])


In [35]:
torch.mm(tensor_A,tensor_B.T)

tensor([[ 23.,  29.,  35.],
        [ 53.,  67.,  81.],
        [ 83., 105., 127.]])

In [36]:


%%time
torch.manual_seed(42)

linear = torch.nn.Linear(in_features=2,
                         out_features=4)
x,y = torch.Tensor([1,2,3]),tensor_A
output = linear(y)
print(f"input shape {x.shape}")
print(f"output shape {output.shape}")
output

input shape torch.Size([3])
output shape torch.Size([3, 4])
CPU times: total: 15.6 ms
Wall time: 10.4 ms


tensor([[2.3378, 0.6147, 0.7451, 0.6186],
        [4.5928, 1.5825, 0.7206, 0.7607],
        [6.8478, 2.5503, 0.6961, 0.9027]], grad_fn=<AddmmBackward0>)

In [37]:
x = torch.arange(10,100,10)
x.type(torch.float32).mean(),x.min(),x.max(),x.sum(),x.argmin(),x.argmax()

(tensor(50.), tensor(10), tensor(90), tensor(450), tensor(0), tensor(8))

In [38]:
torch.mean(x.type(torch.float16)),x.dtype

(tensor(50., dtype=torch.float16), torch.int64)

In [39]:
float_16 = x.type(torch.float16)
float_16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [40]:
int_8 = x.type(torch.int8)
int_8

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

In [41]:
x = torch.arange(1.,8.)
x,x.dtype,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.float32, torch.Size([7]))

In [42]:
x_reshaped = x.reshape(1,7)
x_reshaped , x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [43]:
aa = x.view(1,7)
aa , aa.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [44]:
aa[:,1] = 5
aa , x

(tensor([[1., 5., 3., 4., 5., 6., 7.]]), tensor([1., 5., 3., 4., 5., 6., 7.]))

In [45]:
x_stack = torch.stack([x,x,x,x],dim=1)
x_stack

tensor([[1., 1., 1., 1.],
        [5., 5., 5., 5.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.]])

In [46]:
x_squeezed = x_reshaped.squeeze()
x_squeezed.shape,x_reshaped.shape

(torch.Size([7]), torch.Size([1, 7]))

In [47]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")


x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([1., 5., 3., 4., 5., 6., 7.])
Previous shape: torch.Size([7])

New tensor: tensor([[1., 5., 3., 4., 5., 6., 7.]])
New shape: torch.Size([1, 7])


In [50]:
x_original = torch.rand(size=(224,224,3))
x_permuted = x_original.permute(1,2,0)

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([224, 3, 224])


In [6]:
import torch
x = torch.arange(1,10).reshape(1,3,3)
x , x.shape


(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [7]:
# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}") 
print(f"Second square bracket:{x[0][0]}") 
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket:tensor([1, 2, 3])
Third square bracket: 1


In [10]:
x[:,1]

tensor([[4, 5, 6]])

In [12]:
x[:,:,2]

tensor([[3, 6, 9]])

In [15]:
x[:,1,:] 

tensor([[4, 5, 6]])

In [21]:
x[0,1,1]

tensor(5)

In [26]:
import numpy as np
array = np.arange(1.,8.)
tensor = torch.from_numpy(array)
array , tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [27]:
torch = torch.ones(7)
numpy_tensor = torch.numpy()
torch , numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [29]:
import torch
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.1975, 0.3997, 0.6877, 0.0634],
        [0.2419, 0.1263, 0.4668, 0.7637],
        [0.8704, 0.2925, 0.6972, 0.8354]])

Tensor B:
tensor([[0.5567, 0.2146, 0.0659, 0.7664],
        [0.6628, 0.6757, 0.0456, 0.0108],
        [0.8440, 0.2398, 0.0236, 0.5954]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [32]:
import torch

RANDOM_SEED=51
torch.manual_seed(seed=RANDOM_SEED) 
random_tensor_C = torch.rand(3, 4)

torch.random.manual_seed(seed=RANDOM_SEED) 
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.9872, 0.7404, 0.4463, 0.3556],
        [0.8857, 0.3370, 0.8691, 0.2322],
        [0.7585, 0.5011, 0.0305, 0.3451]])

Tensor D:
tensor([[0.9872, 0.7404, 0.4463, 0.3556],
        [0.8857, 0.3370, 0.8691, 0.2322],
        [0.7585, 0.5011, 0.0305, 0.3451]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [33]:
!nvidia-smi

'nvidia-smi' is not recognized as an internal or external command,
operable program or batch file.
